context:
  id: our-works
  sectionClassList: our-works
  titleConfig:
    title: Примеры наших работ
  filterButtonsSettings:

  categories:
  - slug: all
    name: Все работы

  - slug: septa
    name: Перегородки

  - slug: kitchens
    name: Кухонные фартуки

  - slug: showers
    name: Душевые кабины

  - slug: doors
    name: Двери

  - slug: fences
    name: Ограждения

  - slug: furniture
    name: Мебель

  - slug: panel
    name: Панно

  - slug: mirrors
    name: Зеркала

  - slug: wall-panels
    name: Стеновые панели
