context:
  id: offer
  sectionClassList: offer
  offerImage:
    src: /assets/images/sections/offer/offer1.png
    customClassList: offer__figure
  offerTitle:
    title: специальное предложение
    mods: [offer-label]
  offerObject: "стекло 6мм закаленное с <br>уф-печатью от 2700 рублей/кв.м"
  offerHr:
    customClassList: offer__hr
  offerNote: "Применение: кухонные фартуки, мебельные <br>фасады, покрывные столешницы, экраны для радиаторов, облицовка стен"
