default: mirrors
variants:
- name: mirrors
  context:
    id: mirrors-gallery
    customClassList: mirrors-gallery
    slidesPath: mirrors
    radioPrefix: mirrors
    slides:
    - image: zerkalo_serebro_4mm.jpg
      title: Зеркало серебро
      data:
        name: 2
        material: 8
        depth: 4
        depths: [4,6]
        depthsImages: ['zerkalo_serebro_4mm.jpg', 'zerkalo_serebro_4mm.jpg']
    - image: zerkalo_osvetljonnoe.jpg
      title: Зеркало осветленное
      data:
        name: 2
        material: 13
        depth: 4
        depths: [4,6]
        depthsImages: ['zerkalo_osvetljonnoe.jpg', 'zerkalo_osvetljonnoe.jpg']
    - image: zerkalo_sostarennoe_A1.jpg
      title: Зеркало состаренное
      material: material-A-1.jpg
      data:
        name: 2
        material: 14
        depth: 4
        depths: [4]
        types:
        - name: A1
          material: material-A-1.jpg
          image: zerkalo_sostarennoe_A1.jpg
        - name: A5
          material: material-A-5.jpg
          image: zerkalo_sostarennoe_A5.jpg
        - name: C-1
          material: material-C-1.jpg
          image: zerkalo_sostarennoe_C-1.jpg
        - name: F020-2
          material: material-F020-2.jpg
          image: zerkalo_sostarennoe_F020-2.jpg
        - name: F021
          material: material-F021.jpg
          image: zerkalo_sostarennoe_F021.jpg
        - name: F030-3
          material: material-F030-3.jpg
          image: zerkalo_sostarennoe_F030-3.jpg
        - name: J001
          material: material-J001.jpg
          image: zerkalo_sostarennoe_J001.jpg
        - name: J002
          material: material-J002.jpg
          image: zerkalo_sostarennoe_J-002.jpg
        - name: J021
          material: material-J021.jpg
          image: zerkalo_sostarennoe_J021.jpg
        - name: J033-5
          material: material-J033-5.jpg
          image: zerkalo_sostarennoe_J033-5.jpg
    - image: zerkalo_bronza.jpg
      title: Зеркало бронза
      data:
        name: 2
        material: 9
        depth: 4
        depths: [4]
    - image: zerkalo_seroe.jpg
      title: Зеркало графит
      data:
        name: 2
        material: 10
        depth: 4
        depths: [4]
    - image: zerkalo_krasnoe.jpg
      title: Зеркало красное
      data:
        name: 2
        material: 12
        depth: 4
        depths: [4]
    - image: zerkalo_zoloto_jarkoe.jpg
      title: Зеркало золото
      data:
        name: 2
        material: 11
        depth: 4
        depths: [4]
        types:
        - name: Золото яркое
          image: zerkalo_zoloto_jarkoe.jpg
        - name: Золото шампань
          image: zerkalo_zoloto_shampan-.jpg
- name: glass
  context:
    id: glass-gallery
    customClassList: glass-gallery
    slidesPath: glass
    radioPrefix: glass
    slides:
    - image: 02_steklo_prozrachnoe_10mm.jpg
      title: Стекло прозрачное
      desc: "Универсальное, самое распространенное стекло высочайшей марки М1. С зеленоватым оттенком в торец."
      data:
        name: 1
        material: 1
        depth: 10
        depths: [3,4,5,6,8,10,12]

    - image: 10_steklo_ostvetljonnoe_10mm.jpg
      title: Стекло осветлённое
      desc: "Стекло осветлённое марок Optiwhite и Clearvision - бесцветное идеально прозрачное стекло, не имеющее оттенков. В торец прозрачное, слегка голубое."
      data:
        name: 1
        material: 2
        depth: 10
        depths: [4,5,6,8,10]

    - image: 04_steklo_matovoe_10mm.jpg
      title: Стекло матовое
      desc: "Высококачественное полупрозрачное стекло, объединяет в себе 90% светопропускания, защиту от посторонних глаз и простоту в уходе."
      data:
        name: 1
        material: 3
        depth: 10
        depths: [4,6,8,10]

    - image: 06_steklo_bronza_10mm.jpg
      title: Стекло бронза
      desc: "Тонированное в массе стекло насыщенного тёмно-коричневого цвета с высоким коэффициентом светоотражения."
      data:
        name: 1
        material: 4
        depth: 10
        depths: [4,6,8,10]

    - image: 08_steklo_seroe_10mm.jpg
      title: Стекло серое
      desc: "Тонированное в массе стекло насыщенного тёмно-серого цвета с высоким коэффициентом светоотражения."
      data:
        name: 1
        material: 5
        depth: 10
        depths: [4,6,8,10]
