context:
  id: how
  sectionClassList: how
  titleConfig:
    title: Как мы работаем
  steps:
  - num: '01'
    icon: /assets/images/icons/how/01.png
    title: Онлайн-заказ
    description: "В онлайн-калькуляторе Вы <br>формируете заявку на изделие из <br>стекла или зеркала."

  - num: '02'
    icon: /assets/images/icons/how/02.png
    title: Подтверждение <br>менеджером
    description: "Менеджер проверяет заявку на <br>возможность изготовления, <br>уточняет у Вас необходимую <br>информацию и определяет сроки <br>производства."

  - num: '03'
    icon: /assets/images/icons/how/03.png
    title: Оплата
    description: "Оплата возможна с помощью <br>банковской карты через сайт,<br> наличными в офисе или переводом с расчётного счёта."

  - num: '04'
    icon: /assets/images/icons/how/04.png
    title: Изготовление <br>заказа
    description: "После оплаты 100% стоимости заказа <br>изделие запускается в производство <br>(если оплата произведена до 15:00 <br>– в день оплаты, после 15:00 – в 10:00 <br>следующего рабочего дня)."

  - num: '05'
    icon: /assets/images/icons/how/05.png
    title: Получение <br>заказа / доставка
    description: "Выдача заказов осуществляется <br>(с предварительным смс-уведомлением <br>о готовности заказа) ежедневно <br>с 10:00 до 19:00 по адресу г.Москва, <br>Дмитровское шоссе, д.11;<br> доставка пн.-сб. с 10:00 до 18:00."
