context:
  id: about-video
  sectionClassList: about-video
  titleConfig:
    title: Посмотрите видео о компании
  videos:
  - id: ufLLwRVEP_g
    bg: '/assets/images/sections/about-video/about-video__video-thumbnail.jpg'
  - id: ufLLwRVEP_g
    bg: '/assets/images/sections/about-video/about-video__video-thumbnail.jpg'
