context:
  slides:
  - num: 0296
    desc:
      l: '11+8'
      w: '2.5+0.5'
      h: '0.895'
      m: '38'
    schemes: 2

  - num: 0916
    desc:
      l: '7.7+5.7'
      w: '2.5+0.5'
      h: '0.895'
      m: '32'
    schemes: 2

  - num: 2652
    desc:
      l: '6.7+4'
      w: '2.5+0.5'
      h: '0.6'
      m: '47'

  - num: 2850
    desc:
      l: '12.4'
      w: '2.5+0.5'
      h: '0.85'
      m: '35'

  - num: 4678
    desc:
      l: '8.9+6.3'
      w: '2.54+0.46'
      h: '0.9 +0.13;-0.07'
      m: '80.1'
    schemes: 2

  - num: 4693
    desc:
      l: '16.3+7.5'
      w: '3+0.45'
      h: '0.895'
      m: '73'
    schemes: 3

  - num: 4886
    desc:
      l: '14+7'
      w: '2.5+0.5'
      h: '0.98'
      m: '92.6+28.85'

  - num: 5566
    desc:
      l: '9.7+1.4+1.4'
      w: '2.5+0.5'
      h: '0.7'
      m: '35'
    schemes: 3

  - num: 6989
    desc:
      l: '11+6.5'
      w: '2.5+0.5'
      h: '0.895'
      m: '35'

  - num: 8285
    desc:
      l: '6.5+4'
      w: '2.5+0.5'
      h: '0.6'
      m: '45.3'

  - num: 8302
    desc:
      l: '11'
      w: '2.5+0.5'
      h: '0.86'
      m: '40'

  - num: 9328
    desc:
      l: '6.7+5.5'
      w: '2.5+0.5'
      h: '0.65'
      m: '58.5'
    schemes: 3

  - num: 9429
    desc:
      l: '12.5'
      w: '3+0.5'
      h: '0.93'
      m: '77'
    schemes: 2

  - num: 9491
    desc:
      l: '6.5+4'
      w: '2.5+0.5'
      h: '0.6'
      m: '51'
    schemes: 3

  - num: 9631
    desc:
      l: '11.95+6.9'
      w: '2.5+0.5'
      h: '0.9'
      m: '60'

  - num: 9657
    desc:
      l: '7.8+5.3+5.9'
      w: '2.75+0.9'
      h: '0.6'
      m: '80'
