status: ready
context:
  sections:
  - section: about-video
  - section: about-digits
  - section: portfolio
  - section: services
  - section: assortiment
  # # - section: our-works
  # # - section: offer
  # # - section: calculator
  # # - section: how
  # # - section: pay
